# Generated by Django 5.1.4 on 2025-01-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllStatsSalaryCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField(blank=True, null=True, verbose_name='Зарплата')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
            ],
            options={
                'db_table': 'all_stats_salary_city',
            },
        ),
        migrations.CreateModel(
            name='AllStatsSalaryYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField(verbose_name='Зарплата')),
                ('date', models.CharField(max_length=4, verbose_name='Дата')),
            ],
            options={
                'db_table': 'all_stats_salary_year',
            },
        ),
        migrations.CreateModel(
            name='AllStatsTopSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_skill', models.CharField(max_length=255, verbose_name='Навык')),
                ('skill_count', models.IntegerField()),
                ('date', models.CharField(max_length=4, verbose_name='Дата')),
            ],
            options={
                'db_table': 'all_stats_top_skills',
            },
        ),
        migrations.CreateModel(
            name='AllStatsVacanciesCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancies_count', models.IntegerField(blank=True, null=True, verbose_name='Количество вакансий')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
            ],
            options={
                'db_table': 'all_stats_vacancies_city',
            },
        ),
        migrations.CreateModel(
            name='AllStatsVacanciesYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancies_count', models.IntegerField(verbose_name='Количество вакансий')),
                ('date', models.CharField(max_length=4, verbose_name='Дата')),
            ],
            options={
                'db_table': 'all_stats_vacancies_year',
            },
        ),
        migrations.CreateModel(
            name='GeographySalaryCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField(blank=True, null=True, verbose_name='Зарплата')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
            ],
            options={
                'db_table': 'geography_salary_city',
            },
        ),
        migrations.CreateModel(
            name='GeographyVacanciesCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancies_count', models.IntegerField(blank=True, null=True, verbose_name='Количество вакансий')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
            ],
            options={
                'db_table': 'geography_vacancies_city',
            },
        ),
        migrations.CreateModel(
            name='GraphPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_graph', models.ImageField(upload_to='', verbose_name='График')),
                ('graph_name', models.CharField(max_length=255, verbose_name='Название графика')),
            ],
            options={
                'db_table': 'graphs',
            },
        ),
        migrations.CreateModel(
            name='RelevanceSalaryYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField(verbose_name='Зарплата')),
                ('date', models.CharField(max_length=4, verbose_name='Дата')),
            ],
            options={
                'db_table': 'relevance_salary_year',
            },
        ),
        migrations.CreateModel(
            name='RelevanceVacanciesYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancies_count', models.IntegerField(verbose_name='Количество вакансий')),
                ('date', models.CharField(max_length=4, verbose_name='Дата')),
            ],
            options={
                'db_table': 'relevance_vacancies_year',
            },
        ),
        migrations.CreateModel(
            name='SkillsTopSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_skill', models.CharField(max_length=255, verbose_name='Навык')),
                ('skill_count', models.IntegerField()),
                ('date', models.CharField(max_length=4, verbose_name='Дата')),
            ],
            options={
                'db_table': 'skills_top_skills',
            },
        ),
    ]
